apiVersion: mygroup.mydomain.com/v1
kind: Foo
metadata:
  labels:
    app.kubernetes.io/name: foo
    app.kubernetes.io/instance: foo-sample
    app.kubernetes.io/part-of: my-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: my-operator
  name: foo-sample
spec:
  # TODO(user): Add fields here
